package com.marketing.leadscore.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.marketing.leadscore.entity.Customer;
import com.marketing.leadscore.repository.CustomerRepository;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class PDFExportService {

    private final CustomerRepository customerRepository;

    public PDFExportService(CustomerRepository customerRepository) {
        this.customerRepository = customerRepository;
    }

    public byte[] exportPDF() throws Exception {
        Document document = new Document(PageSize.A4, 36, 36, 36, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        PdfWriter.getInstance(document, out);
        document.open();

        Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD, new Color(30, 41, 59));
        Paragraph title = new Paragraph("LeadPulse AI - Marketing Intelligence Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        document.add(new Paragraph(" "));

        List<Customer> customers = customerRepository.findAll();

        Font subFont = new Font(Font.HELVETICA, 12, Font.NORMAL, Color.DARK_GRAY);
        Paragraph subtitle = new Paragraph("Total Leads Tracked: " + customers.size() + " | Generated by LeadPulse AI Engine", subFont);
        subtitle.setAlignment(Element.ALIGN_CENTER);
        document.add(subtitle);

        document.add(new Paragraph(" "));

        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{25, 25, 25, 12, 13});

        Font headerFont = new Font(Font.HELVETICA, 11, Font.BOLD, Color.WHITE);
        String[] headers = {"Name", "Company", "Email", "Score", "Status"};

        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, headerFont));
            cell.setBackgroundColor(new Color(37, 99, 235));
            cell.setPadding(8);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }

        Font cellFont = new Font(Font.HELVETICA, 10, Font.NORMAL, Color.BLACK);
        for (Customer c : customers) {
            PdfPCell nameCell = new PdfPCell(new Phrase(c.getName() != null ? c.getName() : "-", cellFont));
            nameCell.setPadding(6);
            table.addCell(nameCell);

            PdfPCell compCell = new PdfPCell(new Phrase(c.getCompany() != null ? c.getCompany() : "-", cellFont));
            compCell.setPadding(6);
            table.addCell(compCell);

            PdfPCell emailCell = new PdfPCell(new Phrase(c.getEmail() != null ? c.getEmail() : "-", cellFont));
            emailCell.setPadding(6);
            table.addCell(emailCell);

            PdfPCell scoreCell = new PdfPCell(new Phrase(String.valueOf(c.getLeadScore() != null ? c.getLeadScore() : 0), cellFont));
            scoreCell.setPadding(6);
            scoreCell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(scoreCell);

            PdfPCell statusCell = new PdfPCell(new Phrase(c.getLeadStatus() != null ? c.getLeadStatus() : "Cold", cellFont));
            statusCell.setPadding(6);
            statusCell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(statusCell);
        }

        document.add(table);
        document.close();

        return out.toByteArray();
    }
}